/* ------------------------------------------------------------------ *
 * This migration intentionally runs no SQL.
 *
 * drizzle/meta/0000_snapshot.json had drifted badly out of date: every
 * migration from 0001 onward was hand written as a .sql file rather
 * than generated by drizzle-kit, so the snapshot drizzle-kit uses for
 * its own diffing was never updated past the very first migration.
 * Running `drizzle-kit generate` against that stale snapshot produced
 * a 129 statement migration that looked like it was creating 13 tables,
 * dozens of facilities columns, and several enum values from scratch.
 *
 * Checked directly against the live production database on 2026-10-05
 * and every one of those tables, columns and enum values was already
 * there -- this was pure bookkeeping drift, not a real gap. The one
 * genuinely new table it found, specialist_team_members, already has
 * its own real migration at 0024_specialist_team_members.sql, so it
 * was removed here rather than created twice.
 *
 * This migration exists only so drizzle's own tracking table records
 * it as applied, which lets meta/0025_snapshot.json (written alongside
 * this file) become the new, accurate baseline for every future
 * `drizzle-kit generate` diff.
 * ------------------------------------------------------------------ */
